### ISSUE TITLE
 caffe: symbol lookup error: caffe: undefined symbol: _ZN6google14FlagRegistererC1EPKcS2_S2_S2_PvS3_

### ISSUE THREAD

**Issue by monajalal** [cleardusk/EmotionChallenge#3]
Additionally, after I run

```
 1168  cd cnn/
 1169  ./prepare_data.py
 1192  ./train_val.sh
```

I get this error:
`[jalal@goku cnn]$ ./train_val.sh caffe: symbol lookup error: caffe: undefined symbol: _ZN6google14FlagRegistererC1EPKcS2_S2_S2_PvS3_`

Do you how should this be fixed?

**Comment by cleardusk** [comment]
It seems that you did not compile your caffe with python layer support successfully. Try to modify `makefile` or `CMakeLists.txt`.
