### ISSUE TITLE
FG2020 Compound Emotion Challenge participant

### ISSUE THREAD

**Issue by yuzehui1996** [cleardusk/EmotionChallenge#5]
我是FG2020复合表情的参赛者，请问你有上一届比赛的论文模板吗？另外最终测试集的解压密码也没有公布，想请问一下上一届的比赛最终测试阶段是什么流程？

**Comment by cleardusk** [comment]
上一届比赛的论文模板就是FG的模板；比赛最终测试阶段记不大清楚了，是在colab平台。
